### ISSUE TITLE
Are the checkpoints pre-trained weights or weights of the model itself?

### ISSUE THREAD

**Issue by sdhossain** [atonderski/lidarclip#11]
Sorry if this question's been answered elsewhere - I wanted to know if the checkpoints are the models trained on the LIDAR data - or if it was just initializations?

**Comment by sdhossain** [comment]
Am assuming it's just weights trained on the ONCE dataset.

**Comment by atonderski** [comment]
Yeah, these are the weights from training on ONCE lidar data
