### ISSUE TITLE
Dockerfile pytorch and pytorch lightening version

### ISSUE THREAD

**Issue by tisharSinha** [atonderski/lidarclip#2]
Hello, what version of pytorch and pytorch lightening is required because when I run the dockerfile everything is on pytorch 1.9 but when installing pytorch lightening it updates the pytorch to the latest version 2.0.1 and that gives a lot of errors with previous dependencies related to pytorch 1.9.0.

**Comment by georghess** [comment]
Hi,
Sorry for the slow reply. We are running pytorch 1.9.0 and pytorch lightning 1.6.2. I've updated the docker file to clarify this.

**Comment by georghess** [comment]
@tisharSinha, have you got it up and running? I've updated the instructions and docker file slightly, as per #1

**Comment by georghess** [comment]
Closing for now, feel free to reopen if you need any assistance.
