### ISSUE TITLE
NuScenes Training parameters

### ISSUE THREAD

**Issue by stef-hoer** [atonderski/lidarclip#4]
Hi, 
thanks for sharing your great work!

I'd like to know more how you trained LidarCLIP on the nuscenes dataset.
Since the dataset is a lot smaller, I imagine you trained for more epochs.
Could you elaborate which parameters are different compared to training on the ONCE dataset?

**Comment by atonderski** [comment]
Hi!
We tried to perform as many training iterations for NuScenes as we did for ONCE, so as you said it was a lot more epochs. Other than that, all parameters were kept the same for simplicity :)
