### ISSUE TITLE
Dockerfile with mmcv-full

### ISSUE THREAD

**Issue by ooodnakov** [atonderski/lidarclip#6]
Dockerfile is no longer working since 
https://download.openmmlab.com/mmcv/dist/cu113/torch1.9.0/index.html
doesn't resolve.
It seems that mmcv no longer supports torch 1.9

**Comment by georghess** [comment]
Hi,
Thanks for raising this issue! I think [https://download.openmmlab.com/mmcv/dist/cu111/torch1.8/index.html](https://download.openmmlab.com/mmcv/dist/cu111/torch1.8/index.html) should work without any issues, but I do not have the time to test it currently. If you try it, please let me know if you run into any issues.

**Comment by YhQIAO** [comment]
you can use mirror
