### ISSUE TITLE
ValueError: Expected positive integer steps_per_epoch, but got 0

### ISSUE THREAD

**Issue by lawrence-ff** [atonderski/lidarclip#8]
Hi, I follow the README and I have this error while training.
Is there any solution for this error?
I appreciate your help! I'm excited to try out your code!
![微信图片_20240127174126](https://github.com/atonderski/lidarclip/assets/145632739/6621fa65-4dab-4c6d-b520-1903dd7e0338)

![微信图片_20240127174139](https://github.com/atonderski/lidarclip/assets/145632739/5add17d5-61bf-4e38-9026-c1e277346287)

Is there an imagesets file please, can't read the sequences and frames, thanks!

**Comment by georghess** [comment]
Yes it looks like the code can't find your dataset. You can find the ImageSets folder at https://github.com/once-for-auto-driving/once_devkit. Thanks for pointing this out, I've updated the readme as well.
